version: '3.8'
services:
  postgresql:
    image: 'postgres:17.7'
    container_name: "student_record_db"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      # POSTGRES_PORT: ${POSTGRES_PORT}
    ports: 
      - "${POSTGRES_PORT}:5432"
